### PR TITLE
frontend: Implement angular frontend module

### LINKED ISSUE #13: frontend: Implement an angularjs frontend module.
We should implement an angularjs frontend module that can use the clouwaypush backend.

Some changes to the backend will also be needed for successful integration.

### PR DESCRIPTION
**Pull request by stefan-dimitrov**
Closes #13

### CODE REVIEW

**Comment by stefan-dimitrov** [comment]
The code is ready for review.

**Comment by stefan-dimitrov** [comment]
I'm having a problem when opening a channel when deployed to appengine - server generates a channel token, it is correctly transported to the client, __but__ when client calls gae channel api to open channel the `onopen` handler is never called. Sending an event also does not trigger the `onmessage` handler.
Running on local dev server everything works normally, but on appengine the angular channel never gets opened.

The GWT channel events get processed correctly, no problem with them.

**Comment by stefan-dimitrov** [comment]
Turns out I'm hitting a limitation for the GAE Channel Api that allows only one open channel per client (https://cloud.google.com/appengine/docs/java/channel/#Java_Caveats). The GWT client is opening a channel before angular does which prevents the second channel from connecting.

So to use both GWT and angular clients, they have to share the same channel connection.

**Comment by mlesikov** [comment]
LGTM

**Pull request merged**
